services:
  docker-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-discord-bot
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./settings:/app/settings
    environment:
      - NODE_ENV=production
