services:
  docker-discord-bot:
    # image: anshuljkt1/docker-discord-bot:1.2.3-beta11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-discord-bot
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./settings:/app/settings
    environment:
      NODE_ENV: development
      HEALTH_CHECK_PORT: 3021
    ports:
      - 9229:9229
      - 3021:3021
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3021/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    # user: "501:20"    # Needs to run as root for now...