services:
  docker-discord-bot:
    build:
      context: ./docker-discord-bot
      dockerfile: Dockerfile
    container_name: docker-discord-bot
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./settings:/app/settings
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - ADMIN_ID=${ADMIN_ID}
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
