name: docker-discord-bot
services:
  ddbot:
    image: anshuljkt1/docker-discord-bot:latest
    container_name: docker-discord-bot
    volumes:
      - /volume2/docker/docker-discord-bot/settings:/app/settings/:rw
      - /var/run/docker.sock:/var/run/docker.sock
    # user: "501:20"    # Needs to run as root for now...
    environment:
      NODE_ENV: production
      HEALTH_CHECK_PORT: 3021
    ports:
      - 9229:9229
      - 3021:3021
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3021/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    # labels:
    #   - wud.watch=true
    #   - wud.watch.digest=true
    #   - wud.trigger.include=autorun,minute:minor
    restart: unless-stopped
    networks:
      - swagSSL
networks:
  swagSSL:
    external: true