services:
  docker-discord-bot:
    # image: anshuljkt1/docker-discord-bot:1.2.3-beta11
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-discord-bot
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./settings:/app/settings
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
    # user: "501:20"    # Needs to run as root for now...